[package]
name = "core"
version = "0.1.0"
authors = ["suren <suren>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0" 